see_tl3_progress:
  see_tl3_progress_enabled:
    default: false
    client: true
  progress_bar_color_light:
    default: "green"
    type: string
    required: true
    client: true
  progress_bar_color_dark:
    default: "green"
    type: string
    required: true
    client: true
  progress_bar_background_color_light:
    default: "darkgray"
    type: string
    required: true
    client: true
  progress_bar_background_color_dark:
    default: "lightgray"
    type: string
    required: true
    client: true
  modal_button_icon:
    default: "circle-info"
    type: string
    required: true
    client: true
  show_verbose_tl3_progress:
    default: false
    type: bool
    client: true
  show_locked_at_trust_level:
    default: false
    type: bool
    client: true
  modal_bottom_text:
    default: ""
    type: string
    textarea: true
    required: false
    client: true
  show_next_closest_stat:
    default: false
    type: bool
    client: true
  show_warning_when_tl3_requirements_low:
    default: false
    type: bool
    client: true
  show_warning_when_user_has_muted_topics_and_posts:
    default: false
    type: bool
    client: true
  low_tl3_stats_minimum:
    default: 5
    type: integer
    client: true
